### PR TITLE
Drop down

### PR DESCRIPTION
**Pull request by dhruv8433**
## Pull Request for WebMasterLog 💡

Enhancement 🧑‍💻: We can provide drop down list instead of static opetaions in single line #183

### Issue Title:  Enhancement 🧑‍💻: We can provide drop down list instead of static opetaions in single line

- **Name of the project** :  WebMaster
- **Category:**  Update ui
- **Name:**  Dhruv R Soni
- **GitHub ID:**  https://github.com/dhruv8433
- **Idenitfy yourself:** 

Closes: #183 

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

- created drop down for responsive devices
- update color of drop down as per theme

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested? ⚙️

- check output in responsive devices

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄

for all option selected we got 
image

for easy option
image

for medium
image

and for hard option
image

### CODE REVIEW

**Comment by dhruv8433** [comment]
please inform me if you need any kind of improvement

**Comment by dhruv8433** [comment]
@Avdhesh-Varshney 

Please check it and merge it

**Review by Avdhesh-Varshney — COMMENTED** [review]
@dhruv8433 I think you have still raised the same changes in the pr.
Not Approved. I will not tell you again and again, either change the code as mentioned in earliest prs or communicate to other contributors as well on discord server.

**Comment by dhruv8433** [comment]
@Avdhesh-Varshney 

i pulled newly added code and change style of drop down
set dropdown theme as option theme
you can check that

image

image

image

**Comment by dhruv8433** [comment]
please check that and merge that

**Review by Avdhesh-Varshney — APPROVED** [review]
@dhruv8433 PR Approved 🎉

**Comment by Avdhesh-Varshney** [comment]
@dhruv8433 Carefully linked your pr.

**Comment by dhruv8433** [comment]
Thank You : )

**Pull request merged**
