### PR TITLE
JWT Authenticator with Role based Authorization Issue 122

### PR DESCRIPTION
**Pull request by Pulkit95700**
### Issue Title: JWT Authenticator with Role based Authorization

- **Name of the project** : JWT Authentication with Roles API
- **Category:** NodeJs, API, ExpressJs, MongoDB
- **Name:** Pulkit Gupta
- **GitHub ID:** Pulkit95700
- **Idenitfy yourself:** GSSOC

Closes: 122

### Describe the add-ons or changes you've made 📃
Created full Project for JWT authentication

Directory Structure
- images 
   - contains the images for the Working.md file in base directory of the project
- src
   - index.js
   - constants.js
   - app.js
   - utils
       - ApiError.js
       - ApiResponse.js
       - asyncHandler.js
   - controllers
       - user.controller.js
   - db 
       - index.js
   - middlewares
       - auth.middleware.js
       - permit.middleware.js
   - models
       - user.model.js
   - routes
       - user.routes.js
   - .env
   - package.json
   - package-lock.json
   - Working.md
  

### How Has This Been Tested? ⚙️

This API has undergone extensive testing using Postman, covering secure endpoints and ensuring all functions are bug-free. We've also conducted end-to-end logic testing to ensure smooth operation.
### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Screenshots 📷

You can view the Working.md file in my pull request. It contains all the images for the working API

### Note to reviewers 📄

This api helps user to get a modern starting project for production use. This is a standard setup for any production level project. The different files are used to handle different functions. You can clone it to get started on your project quickly.

### CODE REVIEW

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
@Pulkit95700 
- Directory structure is well maintained. 
- Creating `Intermediate` directory is perfect and 
- Also attach the name of project in README is also perfect.
-----

- But you have commit in main branch not create your own branch.
- No screenshot has added as mention in guidelines.
- Directory name should be "JWT-Authenticator-With-Roles".
- Issue is not properly linked.
- Change the name of `Working.md` to `README.md` and follow the README template as mentioned in guidelines. OK.

**Comment by Avdhesh-Varshney** [comment]
@Pulkit95700 Properly read the guidelines and again create the new pr.

**Comment by Pulkit95700** [comment]
Thanks @Avdhesh-Varshney for telling the required changes. Will fix those and create the new pr.

**Comment by Pulkit95700** [comment]
Could you please also tell me is there any specific name format which should i follow to name the branch?

**Comment by Avdhesh-Varshney** [comment]
@Pulkit95700 there is no such specific rules for branch names.
If you feel any queries, go through other successful merged prs and properly go through guidelines.

**Pull request closed without merging**
