### PR TITLE
Added Flipkart clone

### PR DESCRIPTION
**Pull request by anagha-chaudhari**
Closes: #380 

- **Title** : Flipkart clone
- **Name:** : Anagha Chaudhari
- **Idenitfy yourself:** : GSSOC'24 contributor

### Describe the add-ons or changes you've made 📃
Created a clone of flipkart website

### Screenshots 📷
screenshot

### Type of change ☑️
What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️
- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄
I've made few changes accordingly this time. I request you to please review the PR once again

### CODE REVIEW

**Comment by anagha-chaudhari** [comment]
@Avdhesh-Varshney Please review it

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
@anagha-chaudhari enlist your project in the readme file of `Front-end-Projects`

**Comment by anagha-chaudhari** [comment]
@Avdhesh-Varshney Yes I have enlisted the project now, please check

**Review by Avdhesh-Varshney — APPROVED** [review]
@anagha-chaudhari PR Approved 🎉

**Comment by anagha-chaudhari** [comment]
Thank you very much @Avdhesh-Varshney

**Pull request merged**
