### PR TITLE
Interactive drawing website

### PR DESCRIPTION
**Pull request by aditya-bhaumik**
Closes: #471 

- **Title** : Interactive drawing website
- **Name:** :  Aditya Bhaummik
- **Idenitfy yourself:** :  GSSOC

### Describe the add-ons or changes you've made 📃
This website is an advanced interactive drawing tool that allows users to create digital art directly in their browser. It features a responsive design, various drawing tools including pen, eraser, and color picker, as well as options to undo, redo, save, and load drawings. Users can customize brush sizes and colors, ensuring a flexible and enjoyable drawing experience.

### How Has This Been Tested? ⚙️

i have tested it in my local machine 

### Screenshots 📷

image

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [ ] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] My changes generate no new warnings.

### CODE REVIEW

**Comment by aditya-bhaumik** [comment]
@Avdhesh-Varshney please review this pull request

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
resolve merge conflicts

**Comment by aditya-bhaumik** [comment]
@Avdhesh-Varshney i have resolved the conflicts please merge my pull request

**Comment by aditya-bhaumik** [comment]
@Avdhesh-Varshney please merge my pull requesti have resolved all the conflics

**Review by Avdhesh-Varshney — APPROVED** [review]

**Pull request merged**
