### PR TITLE
Amazon clone under Front end basic project ISSUE #947

### PR DESCRIPTION
**Pull request by Suvadip-sana**
Closes: #947 

- **Title:**  Amazon clone
- **Name:**  Suvadip Sana
- **Idenitfy yourself:**   GSSOC-EXT, Hacktoberfest contributor.

### Describe the add-ons or changes you've made 📃
I create new folder that is `Amazon clone`, it's all file along with it's README.md, and also edit the main README.md file

### Screenshots 📷

a

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄

@Avdhesh-Varshney   Please go through  it and add all the labels that is in #947

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
Not create more than 10 commits, otherwise it can't merged

**Comment by Suvadip-sana** [comment]
@Avdhesh-Varshney Solved.

**Comment by Suvadip-sana** [comment]
@Avdhesh-Varshney 
Hey please check and marge

**Comment by Avdhesh-Varshney** [comment]
Folder name is not changed.

**Pull request closed without merging**
