### PR TITLE
created drop down menu for responsive devices and hide that menu in l…

### PR DESCRIPTION
**Pull request by dhruv8433**
@Avdhesh-Varshney 

…arge screens

### Issue Title: 
Enhancement 🧑‍💻: We can provide drop down list instead of static opetaions in single line #183

- **Name of the project** :  WebMasterLog
- **Category:**  Next JS
- **Name:**  Dhruv R Soni
- **GitHub ID:**  https://github.com/dhruv8433
- **Idenitfy yourself:**  GSSOC'24

Closes: #183

### Describe the add-ons or changes you've made 📃
- i created one drop down list that only visible in responsive devices and also hide static options on responsive
- when user click on particular drop down options, the filter applied and all cards shown based on user's option selection

### Type of change ☑️

What sort of change have you made:

1. hide static menu in responsive devices
2. add drop down on responsive devices

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested? ⚙️

- we can check it by see website in responsive devices

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Screenshots 📷

- in large pc screen
image

- in responsive devices
image

### CODE REVIEW

**Comment by dhruv8433** [comment]
@Avdhesh-Varshney please check this and merge it

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
@dhruv8433 loading is done many times, loader is called again and again. Try to resolve it.
Also I think, it's not looks attractive with the theme of the website.

**Comment by dhruv8433** [comment]
ok i will do it

**Comment by dhruv8433** [comment]
@Avdhesh-Varshney 

check this out 
for all option selected we got 
image


for easy option
image

for medium
image

and for hard option
image

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
@dhruv8433 LGTM. But color of `All` is not the dark blue so change it.
Why have you update single quotes into double quotes? and tab size from 4 to 2?
This makes pr review difficult, so always push your updated code only not change the style or formatting. OK.

**Comment by dhruv8433** [comment]
@Avdhesh-Varshney 

as you say i updated `all` bg to light blue
image

and i revert code to signle quote and just add my code below

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
image

`Easy` or any filter is not working?
And still no change in `MainPage.jsx` file?

**Comment by dhruv8433** [comment]
@Avdhesh-Varshney 

now you can check 
medium
image

easy
image


now filter is workin properly

**Comment by dhruv8433** [comment]
Hey @Avdhesh-Varshney ,review it and merged it

**Review by Avdhesh-Varshney — COMMENTED** [review]
@dhruv8433 it's still not looks good and re-create the pr again by updating your forked repository.

**Pull request closed without merging**
