### PR TITLE
Biography of Mahatma Gandhi #57

### PR DESCRIPTION
**Pull request by TanushreeBorase**
# Pull Request for WebMasterLog 💡

## Issue Title: Biography of Mahatma Gandhi

- **Name of the project** : Biography of Mahatma Gandhi
- **Category: Basic Frontend Project ( HTML and CSS)
- **Name:  Tanushree Borase
- **GitHub ID: https://github.com/TanushreeBorase
- **Idenitfy yourself: JWOC'24 Contributor

Closes: #57 

### Describe the add-ons or changes you've made 📃
I have added a basic project named Biography of Mahatma Gandhi under Front-end-Projects folder.

Give a clear description of what have you added or modifications made: 

I have added html and css files along with images and readme file for project . It include the varios events happened in Gadhi Ji's lige from his birth,education,independence movements,salt march,quit india to his death.

## Type of change ☑️

- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)

## How Has This Been Tested? ⚙️

Describe how it has been tested:
 I have checked whether all the buttons are working and images placed properly in alignment with text style.
Describe how have you verified the changes made: By checking my index.html file and viewing the project made.

## Checklist: ☑️
- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots 📷
video link --> 
https://1drv.ms/v/s!AmV7gUUmUoBXj08rAwEF2mdBdefi?e=sjZuuX

image

image

### CODE REVIEW

**Comment by TanushreeBorase** [comment]
Have I made PR correctly, or I made some error. Pls let me I know.
Thanks for giving me opportunity to work on this issue.

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
@TanushreeBorase LGTM.
There is a little typo error `basic` directory name -> `Basic` other than everything is perfect.
This is required otherwise final website will not interpret this directory which will showcase all the projects.

To stop the overflow of the website use `overflow-x: hidden;` in css of the body.👍

**Comment by TanushreeBorase** [comment]
Should I make a new PR? I did something wrong it seems.

**Review by Avdhesh-Varshney — APPROVED** [review]
@TanushreeBorase There is no mistake from your side. Currently i am deploying the main website. That's why it happened.

**Comment by Avdhesh-Varshney** [comment]
PR Approved. 🎉

**Pull request merged**
