### PR TITLE
added 404 page

### PR DESCRIPTION
**Pull request by Jagpreet153**
Closes: #402  

- **404 Error Page** : 
- **Name:** : Jagpreet Singh Khurana
- **Idenitfy yourself:** : GSSOC'24

### Describe the add-ons or changes you've made 📃
Added a home button and animation of 404 page using lottie animation 

### How Has This Been Tested? ⚙️
I have checked the changes locally on my environment

### Screenshots 📷
Screenshot 2024-06-28 143651

### Type of change ☑️

What sort of change have you made:
- [x] New feature (non-breaking change which adds functionality)

### Checklist: ☑️
- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄
Kindly review this PR

### CODE REVIEW

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
@Jagpreet153 working is good. But page is not looks nice.

**Comment by Jagpreet153** [comment]
Ok @Avdhesh-Varshney . I will add another animation

**Comment by Jagpreet153** [comment]
@Avdhesh-Varshney Is it looking ok

Screenshot 2024-06-30 113922

**Comment by Avdhesh-Varshney** [comment]
@Jagpreet153 you can review your deployed pr [link](https://web-master-log-git-fork-jagpre-7e034a-avdheshvarshneys-projects.vercel.app/king). It's similar to the last view.

**Comment by Jagpreet153** [comment]
Ok @Avdhesh-Varshney . I have requested access

**Comment by Jagpreet153** [comment]
@Avdhesh-Varshney I have changed the animation to this... Kindly have a review.

> @Avdhesh-Varshney Is it looking ok
> 
> Screenshot 2024-06-30 113922

I have changed the animation to this . Kindly have a review .

**Review by Avdhesh-Varshney — COMMENTED** [review]
@Jagpreet153 looks good. But i've rebase the code of website yesterday. So, there're a lots of conflicts. You have to raise your pr again and not commit in `main` branch.

Also, use only boostrap css only. I've removed css files of all components which are un-necessary.

**Comment by Jagpreet153** [comment]
Ok @Avdhesh-Varshney I would be raising PR agian

**Pull request closed without merging**
