### PR TITLE
Added task manager app

### PR DESCRIPTION
**Pull request by mehul-m-prajapati**
Closes: #814 

- **Title:** Task manager app
- **Name:** Mehul Prajapati
- **Idenitfy yourself:** GSSOC-EXT , Hacktoberfest

### Screenshots 📷
screenshot

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
Enlist your project in Angular projects readme file and convert ss png to webp

**Comment by mehul-m-prajapati** [comment]
> [Avdhesh-Varshney](/Avdhesh-Varshney)

@Avdhesh-Varshney : okay, done.

**Comment by mehul-m-prajapati** [comment]
> Enlist your project in Angular projects readme file and convert ss png to webp

@Avdhesh-Varshney : please review and move ahead with this one.

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
image

Properly write your readme file

**Comment by mehul-m-prajapati** [comment]
@Avdhesh-Varshney : Fixed readme now. please review the same.

**Review by Avdhesh-Varshney — APPROVED** [review]

**Pull request merged**
