### PR TITLE
Stopwatch website

### PR DESCRIPTION
**Pull request by A-b-i-r-a-m-i-G-S**
### Issue Title: Stopwatch using Vanilla JS

- **Name of the project** : Stopwatch
- **Category:** Vanilla JS
- **Name:** Abirami Gurushanker
- **GitHub ID:** @A-b-i-r-a-m-i-G-S
- **Identify yourself:** GSSOC'24 contributor

Closes: #112

### Description 📃

The project is a sleek and efficient stopwatch application built using HTML, CSS, and JavaScript. Designed with simplicity and functionality in mind, it allows users to accurately track time with precision. The elapsed time is displayed along with a play, pause and restart button. 

### Type of change ☑️
What sort of change have you made:
- [x] Created new Vanilla JS project

### How Has This Been Tested? ⚙️
The website has been tested for various edge cases to ensure that the timer functions properly. It has also been tested for responsiveness for various viewports.

### Checklist: ☑️
- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Screenshots 📷
image

### CODE REVIEW

**Comment by A-b-i-r-a-m-i-G-S** [comment]
@Avdhesh-Varshney can you have a look at the PR and merge it if it's satisfactory?

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
@A-b-i-r-a-m-i-G-S everything is perfect but
image

properly link your image and update the [database](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/database/vanilla.json)

**Comment by A-b-i-r-a-m-i-G-S** [comment]
@Avdhesh-Varshney the requested changes have been made

**Review by Avdhesh-Varshney — APPROVED** [review]
@A-b-i-r-a-m-i-G-S PR Approved 🎉
But from next time, create your seprate branch apart from `main` branch for each issue and follow the guidelines carefully.

**Pull request merged**
