### PR TITLE
Added Youtube Video Downloader

### PR DESCRIPTION
**Pull request by Asymtode712**
### Issue Title: #205 

- **Name of the project** : Youtube Video Downloader
- **Category:** NodeJS
- **Name:** Siddheya Kulkarni
- **GitHub ID:** https://github.com/Asymtode712
- **Idenitfy yourself:** GSSOC contributor

Closes: #205 

### Describe the add-ons or changes you've made 📃

This is a simple Youtube Video Downloader built using HTML, CSS, JS and NodeJS which helps to download a youtube video in preferred quality using video URL.

### Type of change ☑️

What sort of change have you made:

- [X] New feature (non-breaking change which adds functionality)

### How Has This Been Tested? ⚙️
I have test this project on my local machine.

### Checklist: ☑️

- [X] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] This PR does not contain plagiarized content.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] My changes generate no new warnings.

### Screenshots 📷
yt

### Note to reviewers 📄
Please review and merge this PR if it is good to go

### CODE REVIEW

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
@Asymtode712 move this project inside the `intermediate` directory.
Also mention this project in the Node-JS readme file.

**Comment by Asymtode712** [comment]
@Avdhesh-Varshney Done with the changes please review

**Comment by Avdhesh-Varshney** [comment]
@Asymtode712 don't create un-necessary commits. You can move the project in 1 commit also.
Create another pr. PR not approved.

**Comment by Asymtode712** [comment]
@Avdhesh-Varshney Apologies, will create a new PR soon

**Pull request closed without merging**
