### PR TITLE
Added the feature to auto comment on pr merged 

### PR DESCRIPTION
**Pull request by suhanipaliwal**
### Issue Title: Auto Commenting when a PR is merged 

- **Category:** Documentation
- **Name:** Suhani Singh Paliwal
- **GitHub ID:** suhanipaliwal
- **Idenitfy yourself:** GSSOC Contributor

Closes: #177 

### Describe the add-ons or changes you've made 📃

I have added auto-comment-on-pr-merge.yml in .github/workflows directory. This file will add the feature of auto commenting when a pr is merged.

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
@suhanipaliwal can you comment on the issue when the linked pr is merged?
I don't like to comment on the merged pr.

**Comment by Avdhesh-Varshney** [comment]
@suhanipaliwal are you working on it?

**Comment by AkhilaSunesh** [comment]
I would like to work on this issue. If it is not taken by anyone else.
GSSOC'24

**Comment by suhanipaliwal** [comment]
> @suhanipaliwal are you working on it?

I will complete this issue by tomorrow. Sorry for being inactive. My exams were going on.

**Comment by Avdhesh-Varshney** [comment]
@suhanipaliwal not as expected.

**Pull request closed without merging**
