### PR TITLE
Created ToDo list

### PR DESCRIPTION
**Pull request by Bishal-35**
# Pull Request for WebMasterLog 💡

## Issue Title: 
To Do Application using React Js

- **Name of the project** : To Do Application
- **Category:** ReactJs
- **Name:** Bishal Karmakar
- **GitHub ID:** https://github.com/Bishal-35
- **Idenitfy yourself:** Developer

Closes: 
#10

### Describe the add-ons or changes you've made 📃

Created a React application using ReactJs which lets the user to create a ToDo List

## Type of change ☑️

What sort of change have you made:

-  Created react application which creates a todo list

## How Has This Been Tested? ⚙️

It has been tested it with all the possible ways available.

## Checklist: ☑️

- My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- This PR does not contain plagiarized content.
- I have performed a self-review of my own code.
- I have commented my code, particularly wherever it was hard to understand.
- I have made corresponding changes to the documentation.
- My changes generate no new warnings.
- I have added things that prove my fix is effective or that my feature works.
- Any dependent changes have been merged and published in downstream modules.

## Screenshots 📷

Screenshot 2024-02-20 212451

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
> @Avdhesh-Varshney Why am i not able to push the codes. Instead it is pushing the folder

Delete the repo from your system and again clone it. Then make the pull request and push the code.

**Comment by Avdhesh-Varshney** [comment]
@Bishal-35 Talk to me on discord server of JWOC and try to delete your fork from github and again fork and clone the repo. Then try to push your code and create another pull request.

**Comment by Bishal-35** [comment]
Can't find JWOC discord server link

**Comment by Avdhesh-Varshney** [comment]
Go through JWOC website and contact to program manager OK.

**Pull request closed without merging**
