### PR TITLE
Weather App using React JS

### LINKED ISSUE #117: Weather app using React JS
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : Weather Widget App
:red_circle: **Aim** : Create a weather application using React.js that displays different places weather conditions to the user.
:red_circle: **Tech Stack Used** : React, Material UI (APIs), CSS
:red_circle: **Category** :  React JS

***********************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Sristy Paul
- GitHub Profile Link : https://github.com/sristy17
- What is your participant role? JWoC'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by sristy17**
# Pull Request for WebMasterLog 💡
---
<h3>Issue Title: Weather App using React JS</h3>

---

- **Name of the project** : Weather App
- **Category**: ReactJs
- **Name**: Sristy Paul
- **GitHub ID**:https://github.com/sristy17

Closes #117 

---
**Describe the add-ons or changes you've made 📃**

Created a React application using ReactJs which lets the user to search weather for a place, here the information is passed through api, user ask for request in search box,  the request is then render by api to the user.

---

### Type of change ☑️

What sort of change have you made:

- [x] New feature (non-breaking change which adds functionality)

---
### How Has This Been Tested? ⚙️

It has been tested it with all the possible ways available.

---
### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.

- [x] This PR does not contain plagiarized content.
- [x]  I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

---
### Screenshots 📷

Screenshot 2024-02-25 085119
This is when the weather is sunny or hot.
Screenshot 2024-02-25 085201
This is when the weather is cold.
Screenshot 2024-02-25 090242
This is when the weather is rainy.
Screenshot 2024-02-25 085357
This is when the user request is invalid.

### CODE REVIEW

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
@sristy17 feel the pr template. Don't delete it. And update the readme file as mentioned in guidelines and add the screenshot. That's why I told to check the other merged prs.

**Comment by sristy17** [comment]
> @sristy17 feel the pr template. Don't delete it. And update the readme file as mentioned in guidelines and add the screenshot. That's why I told to check the other merged prs.

Ok will updatee

**Comment by sristy17** [comment]
> @sristy17 feel the pr template. Don't delete it. And update the readme file as mentioned in guidelines and add the screenshot. That's why I told to check the other merged prs.

I have updates everything please check!

Can you please label it under hard?!

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
@sristy17 Change the directory name `Weather-App` in Kebab-Case mentioned in guidelines.
Add 1 screenshot in `.webp` format also with same of directory `Weather-App.webp`.

**Comment by sristy17** [comment]
> @sristy17 Change the directory name `Weather-App` in Kebab-Case mentioned in guidelines. Add 1 screenshot in `.webp` format also with same of directory `Weather-App.webp`.

hey! I made changes regarding screenshots, but am  not getting how to change the directory name, can you please help me with it?

**Comment by sristy17** [comment]
> @sristy17 Change the directory name `Weather-App` in Kebab-Case mentioned in guidelines. Add 1 screenshot in `.webp` format also with same of directory `Weather-App.webp`.

please check!

**Comment by Avdhesh-Varshney** [comment]
@sristy17 For a issue, there are 15 commits and many of them are unnecessary. Directory name is still not changed. Create another pr withing timeline of JWOC, if possible. And properly fill the pr template without any unnecessary deletion.

**Comment by sristy17** [comment]
> @sristy17 For a issue, there are 15 commits and many of them are unnecessary. Directory name is still not changed. Create another pr withing timeline of JWOC, if possible. And properly fill the pr template without any unnecessary deletion.

M not able to change the directory name please help me out with it

**Pull request closed without merging**
