### PR TITLE
Add yellowish neon-style scrollbar

### PR DESCRIPTION
**Pull request by ramith-kulal**
# Pull Request for WebMasterLog 💡

## Issue Title: Add customized scrollbar.

- **Name of the project** : WEB MASTER LOG
- **Category:** CSS
- **Name:** Ramith
- **GitHub ID:** Ramith-kulal
- **Idenitfy yourself:** JWOC Contributor

Closes: #113 

### Describe the add-ons or changes you've made 📃

Added a customized yellowish neon-style scrollbar to enhance the user experience and visual appeal of the website.e

## Type of change ☑️

What sort of change have you made:

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested? ⚙️

Tested on multiple web browsers (Chrome, Firefox, Safari) and different screen sizes to ensure compatibility and responsiveness.
## Checklist: ☑️

- [X] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] This PR does not contain plagiarized content.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added things that prove my fix is effective or that my feature works.

## Screenshots 📷

`BEFORE:
Screenshot 2024-02-23 102041
NOW:
Screenshot 2024-02-23 102024

## Note to reviewers 📄

**Working under JWOC**

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@ramith-kulal try to make it colorful as the colors of the icons of tech stack as angular icon is of red color, light of scrollbar also red colored.

**Comment by Avdhesh-Varshney** [comment]
> so you want me to add different scrollbar color for different tech stack matching its icon color?

Yes

**Comment by ramith-kulal** [comment]
@Avdhesh-Varshney   The scrollbar colors have been updated to harmonize with the icon colors.
Would it be possible to change the label  from "Medium" to "Hard"?. it was pretty complex than i thought tbh, thanks .

**Comment by Avdhesh-Varshney** [comment]
LGTM. PR Approved 🎉

**Comment by ramith-kulal** [comment]
> LGTM. PR Approved 🎉

yeah thanks 🙌

**Pull request merged**
