### PR TITLE
Added z-index to remove overlapping

### PR DESCRIPTION
**Pull request by techy4shri**
Added z-index in css files to remove overlapping of sidebar menu and project cards when the side menu is expanded.

This does not affect the website or the webpage as a whole. See #246

Closes: 246

- **Title** :   #246
- **Name:** : GARIMA
- **Idenitfy yourself:** :GSSOC 2024 Contributor

### Describe the add-ons or changes you've made 📃
Added z-index in css files to remove overlapping of sidebar menu and project cards when the side menu is expanded.

### How Has This Been Tested? ⚙️

Checked by running the project and going to each page and expanding the siedebar menu.
### Screenshots 📷
Screenshot 2024-06-07 144132
Screenshot 2024-06-05 222623 1
Screenshot 2024-06-05 222623 edit
Screenshot 2024-06-05 222623
Screenshot 2024-06-05 230145
Screenshot 2024-06-05 230206
Screenshot 2024-06-06 150217

### Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
@techy4shri but i can't see any such improvement in over-lapping as the cards and sidebar are still over-lapped to each other.

image

**Comment by techy4shri** [comment]
Should I make it so that there is space between them when the sidebar is expanded? So there is a gap between them?

**Comment by Avdhesh-Varshney** [comment]
> Should I make it so that there is space between them when the sidebar is expanded? So there is a gap between them?

yes

**Comment by Avdhesh-Varshney** [comment]
leave it. work on other issues.

**Pull request closed without merging**
