### PR TITLE
RGB Color Slider

### PR DESCRIPTION
**Pull request by AmrutaJayanti**
### Issue Title: Project: RGB Color Slider

- **Name of the project** : RGB Color Slider
- **Category:**  Vanilla
- **Name:**  Amruta Jayanti
- **GitHub ID:** [AmrutaJayanti](https://github.com/AmrutaJayanti)
- **Idenitfy yourself:**  GSSOC Contributor

Closes: #238 

### Describe the add-ons or changes you've made 📃

I added a Markdown Previewer directory in `Vanilla-Js/Basic`

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Screenshots 📷
Screenshot 2024-06-05 124103

### Note to reviewers 📄

Please approve

### CODE REVIEW

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
@AmrutaJayanti mention your project in the readme file of vanilla js projects and also add it in the database file.
It is mandatory to join the discord server as i have mentioned some guidelines there.

**Comment by AmrutaJayanti** [comment]
@Avdhesh-Varshney Made the changes . Please check

**Comment by AmrutaJayanti** [comment]
@Avdhesh-Varshney If you dont mind can you provide me the link to discord server

**Comment by Avdhesh-Varshney** [comment]
> Thank you for submitting your pull request! We'll review it as soon as possible. For further communication, join our discord server https://discord.gg/tSqtvHUJzE.

Here it is.

**Pull request merged**
