### PR TITLE
Added Days between two Dates: #338

### PR DESCRIPTION
**Pull request by Anshika14528**
Closes: #338 

- **Title** : Days between two Dates
- **Name:** : Anshika
- **Idenitfy yourself:** : GSSOC

### Describe the add-ons or changes you've made 📃
Added a Days between two Dates which finds no. of days between two dates.

### How Has This Been Tested? ⚙️
I have tested it on my own

### Screenshots 📷
Screenshot 2024-06-17 at 6 56 00 PM

### Type of change ☑️

- [x] New feature (non-breaking change which adds functionality)

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
@Anshika14528 follow the folder structure as mentioned in guidelines or refer to merged prs of same tech stack.

**Comment by Anshika14528** [comment]
@Avdhesh-Varshney sir, i have made the required changes is it ok now?
screenshot

if it is ok can you please increase its level

**Review by Avdhesh-Varshney — APPROVED** [review]
@Anshika14528 pr approved 🎉

**Comment by Anshika14528** [comment]
Thankyou

**Pull request merged**
