### PR TITLE
CSS Art Gallery

### PR DESCRIPTION
**Pull request by AmrutaJayanti**
### Issue Title:CSS Art Gallery 

- **Name of the project** : CSS Art Gallery
- **Category:**  Vanilla
- **Name:**  Amruta Jayanti
- **GitHub ID:** [AmrutaJayanti](https://github.com/AmrutaJayanti)
- **Idenitfy yourself:**  GSSOC Contributor

Closes: #256 

### Describe the add-ons or changes you've made 📃

I added `CSS-Art-Gallery`

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Screenshots 📷

Screenshot 2024-06-07 165812
Screenshot 2024-06-07 165823

### Note to reviewers 📄

Please approve

### CODE REVIEW

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
@AmrutaJayanti resolve merge conflicts.

**Comment by AmrutaJayanti** [comment]
@Avdhesh-Varshney I think i resolved the conflict . Please approve

**Review by Avdhesh-Varshney — APPROVED** [review]
@AmrutaJayanti PR Approved 🎉

**Comment by Avdhesh-Varshney** [comment]
@AmrutaJayanti Don't create a lots of commits for a single project addition. You can commit them in a single commit.
For the next time, It will not be acceptable.

**Comment by AmrutaJayanti** [comment]
Okay! @Avdhesh-Varshney

**Pull request merged**
