### PR TITLE
Add wikipedia clone

### PR DESCRIPTION
**Pull request by amanver45**
issue #835 
Closes: 
Title: Add Wikipedia clone
- Name: Aman Verma
- Identify yourself:GSSOC Contributor

### Describe the add-ons or changes you've made 📃
ADD WIKIPEDIA CLONE 

### Screenshots 📷
LIGHT MODE Screenshot 2024-10-11 104021
DARK MODE Screenshot 2024-10-11 110939

- [x] My code follows the code style of this project.
- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
Rename `Wikipedia-Clone` and `aw` -> `screenshot`

**Comment by amanver45** [comment]
Changes done

**Comment by amanver45** [comment]
@Avdhesh-Varshney pls  check and merge it

**Comment by Avdhesh-Varshney** [comment]
> Rename `Wikipedia-Clone`

This is to be the folder name

**Comment by amanver45** [comment]
@Avdhesh-Varshney pls  check it

**Comment by amanver45** [comment]
@Avdhesh-Varshney pls  check it I made all the changes

**Comment by amanver45** [comment]
@Avdhesh-Varshney  pls check it sir

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
- Folder name `Wikipedia-clone` -> `Wikipedia-Clone`
- Review main readme file of Vanilla-JS-Projects and enlist according to it. I've recently updated it.
- Don't create more commits. Otherwise it can't be merged in `main` branch.

**Comment by amanver45** [comment]
Screenshot_2024-10-16-18-35-48-252_com android chrome
@Avdhesh-Varshney updated h sir pls check it

**Comment by amanver45** [comment]
@Avdhesh-Varshney  sir already clone ko Clone folder aur readme m update kar diye ghe

**Comment by amanver45** [comment]
@Avdhesh-Varshney  sir pls help

**Comment by amanver45** [comment]
@Avdhesh-Varshney how to resolve this I already updated

**Comment by amanver45** [comment]
@Avdhesh-Varshney pls reply sir

**Comment by amanver45** [comment]
Screenshot_2024-10-16-18-53-50-547_com android chrome
@Avdhesh-Varshney sir changes are done

**Comment by amanver45** [comment]
@Avdhesh-Varshney sir please check and merge it

**Comment by amanver45** [comment]
@Avdhesh-Varshney pls sir

**Comment by amanver45** [comment]
@Avdhesh-Varshney  sir it  my open source event  pls help

**Comment by Avdhesh-Varshney** [comment]
You should use your laptop first. Rename your folder name not only in readme file. Read guidelines properly and review other merged projects in same category.

**Comment by amanver45** [comment]
Screenshot 2024-10-16 191749
already updated sir @Avdhesh-Varshney

**Comment by Avdhesh-Varshney** [comment]
> * Folder name `Wikipedia-clone` -> `Wikipedia-Clone`
> * Review main readme file of Vanilla-JS-Projects and enlist according to it. I've recently updated it.
> * Don't create more commits. Otherwise it can't be merged in `main` branch.

See here `c` letter is in small letter in your folder name. I hope you understood it.
Next, Review the codebase of newly updated [README](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/Vanilla-JS-Projects/README.md) file. Now, enlist your project here.

**Pull request closed without merging**
